### ISSUE TITLE
onRender prop not being called

### ISSUE THREAD

**Issue by nickmisasi** [ClickSimply/react-dynamic-virtual-list#1]
Hi, I've been playing around with this component trying to get it to render my list but I've hit a snag where it seems to just not call its onRender prop.

React 16.3.1 
react-dynamic-virtual-list 1.2.2

Here's my jsx for the component:
```
<DVL
                        onRender={item => <div>{this.renderRow(item)}</div>}
                        items={this.state.employees}
                        windowContainer={true}
/>
```
and the `renderRow` function:
```
 renderRow(item){
        console.log("render row");
        return (
            <Item
                key={item.id}
                id={item.id}
                checked={selected === item.id}
                onChange={this.onChange}
            >
                {item.first_name + ' ' + item.last_name + ' ' + ((this.props.currentUser === item.id) ? '(Me)': '')}
            </Item>
        );
    }
```

I never see the "render now" log leading me to believe this function isn't being called. Any idea what might be happening?

**Comment by only-cliches** [comment]
Not sure, every which way I test it things seem to work fine.

A few things to try:
1. Replace `this.state.employees` with an array of fixed values, see if that works
2. Replace the `renderRow` method with a super simple inline function.

Basically remove complexity until we get a result, then we'll see what's causing the issue.

You might just drop the below code from the readme into your app and see if that at least renders, then add elements back one at a time.
```ts
<DVL
    onRender={item => <div>{item.name}</div>}
    items={[{name: "Billy"}, {name: "Joel"}]}
    windowContainer={true}
/>
```

**Comment by nickmisasi** [comment]
Tried just the very primitive way, and still wasn't able to get it to work. The onRender function seems to never be called for some reason. Likely could be because I was bolting this module onto a pretty well established code-base. I'll try Monday on just a simple create-react-app project. Hoping I can get this going, this module seems like one of the nicer ones I've found for dynamic virtual lists.

**Comment by only-cliches** [comment]
Interesting,  are there any console errors?

If you're comfortable with sharing your source code with me I'd be happy to take a look and see whats going on.

I also just pushed an update, v1.2.3 with some changes to the rendering scripts.  You might give it a try.

**Comment by nickmisasi** [comment]
No console errors. It's as if the component isn't there. Very weird. I unfortunately can't share the code, but if I can replicate the error in a simple project on Monday I'll be able to share that.

**Comment by only-cliches** [comment]
I was just thinking... are you using Babel by chance?  Might try playing with the import statement, one of these will probably end up working:

```ts
import * as DVL from "react-dynamic-virtual-list";
import DVL from "react-dynamic-virtual-list";
import { DVL } from "react-dynamic-virtual-list";
```

I normally use Typescript but I've noticed Babel imports are sometimes different for some reason...

**Comment by only-cliches** [comment]
Marking this resolved since it's been inactive for so long, feel free to reopen if you find further info.
